spring.application.name=moyeorak
# ===============================
# = DATABASE CONNECTION SETTINGS =
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/moyeorak_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.url=jdbc:mysql://goorm-mysql.c92y0sa8e7t2.ap-northeast-2.rds.amazonaws.com:3306/moyeorak_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=choi
spring.datasource.password=1q2w3e4r!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = REDIS SETTINGS    =
# ===============================
#spring.redis.host=goorm-redis.m98tqf.ng.0001.apn2.cache.amazonaws.com
#spring.redis.port=6379
#spring.cache.type=redis

# ===============================
# = SQS SETTINGS    =
# ===============================
sqs.queue.url=https://sqs.ap-northeast-2.amazonaws.com/004407157704/goorm-rental-sqs

# ===============================
# = JPA / HIBERNATE SETTINGS    =
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# = SERVER SETTINGS             =
# ===============================
server.port=8080

jwt.secret=Y29tZXhhbXBsZWtleTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MA==

management.endpoints.web.exposure.include=health,info

spring.cloud.aws.sqs.enabled=false
